# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autograder_gui.ui'
#
# Created: Sun May  1 14:11:57 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName(_fromUtf8("Window"))
        Window.resize(896, 531)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Window)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Window)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.directorybox = QtGui.QLineEdit(Window)
        self.directorybox.setObjectName(_fromUtf8("directorybox"))
        self.verticalLayout.addWidget(self.directorybox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.browsebutton = QtGui.QPushButton(Window)
        self.browsebutton.setObjectName(_fromUtf8("browsebutton"))
        self.horizontalLayout.addWidget(self.browsebutton)
        self.clearbutton = QtGui.QPushButton(Window)
        self.clearbutton.setObjectName(_fromUtf8("clearbutton"))
        self.horizontalLayout.addWidget(self.clearbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(Window)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.scriptlist = QtGui.QTextBrowser(Window)
        self.scriptlist.setObjectName(_fromUtf8("scriptlist"))
        self.verticalLayout.addWidget(self.scriptlist)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_15 = QtGui.QLabel(Window)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 1, 1, 1)
        self.commentcheck = QtGui.QCheckBox(Window)
        self.commentcheck.setObjectName(_fromUtf8("commentcheck"))
        self.gridLayout_2.addWidget(self.commentcheck, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(Window)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 1, 1, 1, 1)
        self.functioncheck = QtGui.QCheckBox(Window)
        self.functioncheck.setObjectName(_fromUtf8("functioncheck"))
        self.gridLayout_2.addWidget(self.functioncheck, 1, 0, 1, 1)
        self.comment_freq = QtGui.QLineEdit(Window)
        self.comment_freq.setObjectName(_fromUtf8("comment_freq"))
        self.gridLayout_2.addWidget(self.comment_freq, 0, 2, 1, 1)
        self.timeout_box = QtGui.QLineEdit(Window)
        self.timeout_box.setObjectName(_fromUtf8("timeout_box"))
        self.gridLayout_2.addWidget(self.timeout_box, 0, 4, 1, 1)
        self.avg_func_len = QtGui.QLineEdit(Window)
        self.avg_func_len.setBaseSize(QtCore.QSize(0, 0))
        self.avg_func_len.setObjectName(_fromUtf8("avg_func_len"))
        self.gridLayout_2.addWidget(self.avg_func_len, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(Window)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 3, 1, 1)
        self.define_inout = QtGui.QPushButton(Window)
        self.define_inout.setObjectName(_fromUtf8("define_inout"))
        self.gridLayout_2.addWidget(self.define_inout, 1, 4, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 1)
        self.gridLayout_2.setColumnMinimumWidth(1, 1)
        self.gridLayout_2.setColumnMinimumWidth(2, 3)
        self.gridLayout_2.setColumnMinimumWidth(3, 1)
        self.gridLayout_2.setColumnMinimumWidth(4, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.label_5 = QtGui.QLabel(Window)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.StatusBox = QtGui.QTextBrowser(Window)
        self.StatusBox.setObjectName(_fromUtf8("StatusBox"))
        self.verticalLayout_2.addWidget(self.StatusBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_10 = QtGui.QLabel(Window)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 0, 3, 1, 1)
        self.errorweight = QtGui.QLineEdit(Window)
        self.errorweight.setReadOnly(True)
        self.errorweight.setObjectName(_fromUtf8("errorweight"))
        self.gridLayout.addWidget(self.errorweight, 3, 4, 1, 1)
        self.label_11 = QtGui.QLabel(Window)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(Window)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(Window)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Window)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(Window)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(Window)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_8 = QtGui.QLabel(Window)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.incorrectweight = QtGui.QLineEdit(Window)
        self.incorrectweight.setReadOnly(True)
        self.incorrectweight.setObjectName(_fromUtf8("incorrectweight"))
        self.gridLayout.addWidget(self.incorrectweight, 2, 4, 1, 1)
        self.correctweight = QtGui.QLineEdit(Window)
        self.correctweight.setReadOnly(True)
        self.correctweight.setObjectName(_fromUtf8("correctweight"))
        self.gridLayout.addWidget(self.correctweight, 1, 4, 1, 1)
        self.linenumbers = QtGui.QLineEdit(Window)
        self.linenumbers.setReadOnly(True)
        self.linenumbers.setObjectName(_fromUtf8("linenumbers"))
        self.gridLayout.addWidget(self.linenumbers, 1, 1, 1, 1)
        self.functionnumbers = QtGui.QLineEdit(Window)
        self.functionnumbers.setReadOnly(True)
        self.functionnumbers.setObjectName(_fromUtf8("functionnumbers"))
        self.gridLayout.addWidget(self.functionnumbers, 2, 1, 1, 1)
        self.commentnumbers = QtGui.QLineEdit(Window)
        self.commentnumbers.setReadOnly(True)
        self.commentnumbers.setObjectName(_fromUtf8("commentnumbers"))
        self.gridLayout.addWidget(self.commentnumbers, 3, 1, 1, 1)
        self.correctnum = QtGui.QLineEdit(Window)
        self.correctnum.setReadOnly(True)
        self.correctnum.setObjectName(_fromUtf8("correctnum"))
        self.gridLayout.addWidget(self.correctnum, 1, 3, 1, 1)
        self.incorrectnum = QtGui.QLineEdit(Window)
        self.incorrectnum.setReadOnly(True)
        self.incorrectnum.setObjectName(_fromUtf8("incorrectnum"))
        self.gridLayout.addWidget(self.incorrectnum, 2, 3, 1, 1)
        self.errornum = QtGui.QLineEdit(Window)
        self.errornum.setReadOnly(True)
        self.errornum.setObjectName(_fromUtf8("errornum"))
        self.gridLayout.addWidget(self.errornum, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(Window)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.directorybox.clear)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        Window.setWindowTitle(_translate("Window", "Autograder", None))
        self.label.setText(_translate("Window", "Directory:", None))
        self.browsebutton.setText(_translate("Window", "Browse", None))
        self.clearbutton.setText(_translate("Window", "Clear", None))
        self.label_2.setText(_translate("Window", "Recognized Scripts:", None))
        self.label_15.setText(_translate("Window", "Comment Frequency", None))
        self.commentcheck.setText(_translate("Window", "Check for Comments", None))
        self.label_16.setText(_translate("Window", "Avg. Function Length", None))
        self.functioncheck.setText(_translate("Window", "Check for functions", None))
        self.label_14.setText(_translate("Window", "Timeout (seconds):", None))
        self.define_inout.setText(_translate("Window", "Define Input/Output Cases", None))
        self.label_5.setText(_translate("Window", "Status:", None))
        self.label_10.setText(_translate("Window", "Number", None))
        self.label_11.setText(_translate("Window", "Lines", None))
        self.label_12.setText(_translate("Window", "Comments", None))
        self.label_13.setText(_translate("Window", "Functions", None))
        self.label_6.setText(_translate("Window", "Correct Answers", None))
        self.label_7.setText(_translate("Window", "Incorrect Answers", None))
        self.label_9.setText(_translate("Window", "Weight", None))
        self.label_8.setText(_translate("Window", "Errors", None))

